#!/usr/bin/perl
use URI;
use strict;
use warnings;
my $str = undef;
my $args = undef;

if (!$ARGV[0]) { print "no arguments provided\n"; exit 1;}
my $url = URI->new("$ARGV[0]");
my $scheme = $url->scheme( );
my $userinfo = $url->userinfo( );
my $hostname = $url->host( );
my $port = $url->port( );
my $query = $url->query( );
if ($query) { $query = "?$query"; }
my $path = $url->path( );
if ($path eq "") {
        $path = undef;
} else {
        $path = " -u $path$query";
}

shift @ARGV;
if (@ARGV) { $args = " @ARGV"}

if ( $scheme eq "https" ) { $str = "-H $hostname -f ok -S$path$args"; }
if ( $scheme eq "http") { $str = "-H $hostname -f ok -p $port$path$args"; }

my $command = "/usr/local/nagios/libexec/check_http";

my $result=`$command $str`;
print $result;

$?=$?>>8;
exit $?;
